M48
; DRILL file {KiCad (6.0.2-0)} date Saturday, September 10, 2022 at 04:34:37 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-10T16:34:37-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0421
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1260
%
G90
G05
T1
X4.9883Y-3.3233
T2
X4.787Y-2.9109
X4.787Y-3.0291
T3
X4.9883Y-3.6167
T4
X5.253Y-2.69
X7.4424Y-2.69
T0
M30
